### ISSUE TITLE
Getting unAutorized when using this

### ISSUE THREAD

**Issue by rostami79** [hfcjweinstock/EncompassREST#12]
I think the code is very interesting and useful 

I was trying to use it and was getting unautorized eventhough I have valid client Id and and secret 

Here is How I used it 

 Session session = new Session("XXX", "XXX", "TEBEXXXX", "XXXX", "XXXX");

 session.StartSession();

I am I doing something wrong here

**Comment by hfcjweinstock** [comment]
Try a fresh pull.  i pushed a change this morning someone else added that should help with this issue.

**Comment by rostami79** [comment]
It worked this time.

very nice !!
