### ISSUE TITLE
Use consistent .NET naming convention

### ISSUE THREAD

**Issue by TylerBrinkley** [hfcjweinstock/EncompassREST#6]
Seeing how Ellie Mae is unlikely to release .NET Language Bindings anytime soon I would like to start contributing to this project. The first thing I noticed when browsing through the source code was the inconsistent naming convention of fields, parameters, and methods.

As is common in .NET I suggest all Types, Methods, Properties, and Public Fields be PascalCase and all parameters and local variables be camelCase. I also suggest non-public fields be camelCase with a leading underscore.

I'd gladly submit a pull request with these changes if you approve.

**Comment by hfcjweinstock** [comment]
go for it.  the only area i would ask you not to mess with is anything in the Data folder. most of that is automatically generated, and may be overwritten in a future iteration.

**Comment by TylerBrinkley** [comment]
I may go through and clean up the formatting. Would that be alright?

**Comment by TylerBrinkley** [comment]
Also, are you opposed to expression-bodied properties and methods?

**Comment by TylerBrinkley** [comment]
Also, what are your feelings on the use of `var`?

**Comment by hfcjweinstock** [comment]
I like it. Simplifies what the code looks like.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by TylerBrinkley** [comment]
Just submitted PR #7 to address some issues with the source code.
